// Builds the ZKSona logo from one source: the mark geometry below + the "zksona" wordmark outlined from
// Bricolage Grotesque ExtraBold. Writes the React path data, the SVG files, the PNG exports and the social images.
// Run: node scripts/build-logo.mjs
import fs from 'node:fs';
import path from 'node:path';
import opentype from 'opentype.js';
import { Resvg } from '@resvg/resvg-js';

const root = path.resolve(import.meta.dirname, '..');
const INK = '#0a0a0b';
const ACCENT = '#f98500';
const PAPER = '#ffffff';
const MIST = '#f3f3f3';
const MINT = '#71cfa3';
const SKY = '#bcefff';

// Mark: an eclipse on an orange tile. A persona (the dark disc) that is there but cannot be seen whole:
// the chain knows something is valid without seeing who. 64-unit grid.
const mark = {
  tile: { x: 0, y: 0, w: 64, h: 64, r: 16 },
  disc: { cx: 30, cy: 34, r: 18 },
  cover: { cx: 40, cy: 26, r: 14 },
};
const markSvg = (tileFill = ACCENT, discFill = INK) =>
  `<rect x="0" y="0" width="64" height="64" rx="16" fill="${tileFill}"/>` +
  `<circle cx="${mark.disc.cx}" cy="${mark.disc.cy}" r="${mark.disc.r}" fill="${discFill}"/>` +
  `<circle cx="${mark.cover.cx}" cy="${mark.cover.cy}" r="${mark.cover.r}" fill="${tileFill}"/>`;

// Wordmark, outlined so it looks the same without the web font
const fontFile = path.join(root, 'node_modules/@fontsource/bricolage-grotesque/files/bricolage-grotesque-latin-800-normal.woff');
const buf = fs.readFileSync(fontFile);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const size = 60;
const tracking = -0.035 * size;
const word = 'zksona';
const glyphs = [...word].map((ch) => font.charToGlyph(ch));
const advance = (i) => {
  const g = glyphs[i];
  const next = glyphs[i + 1];
  const rawKern = next ? font.getKerningValue(g, next) : 0;
  const kern = Number.isFinite(rawKern) ? rawKern : 0;
  return ((g.advanceWidth + kern) / font.unitsPerEm) * size + tracking;
};
const originX = glyphs.map((_, i) => glyphs.slice(0, i).reduce((sum, __, k) => sum + advance(k), 0));
const box = { x1: Infinity, x2: -Infinity };
glyphs.forEach((g, i) => {
  const b = g.getPath(originX[i], 0, size).getBoundingBox();
  box.x1 = Math.min(box.x1, b.x1);
  box.x2 = Math.max(box.x2, b.x2);
});
const n2 = (v) => (Math.round(v * 100) / 100).toString();
const toD = (commands) =>
  commands
    .map((c) => {
      if (c.type === 'M' || c.type === 'L') return `${c.type}${n2(c.x)} ${n2(c.y)}`;
      if (c.type === 'Q') return `Q${n2(c.x1)} ${n2(c.y1)} ${n2(c.x)} ${n2(c.y)}`;
      if (c.type === 'C') return `C${n2(c.x1)} ${n2(c.y1)} ${n2(c.x2)} ${n2(c.y2)} ${n2(c.x)} ${n2(c.y)}`;
      return 'Z';
    })
    .join('');
const WORD_X = 80;
const baseline = 50;
const wordD = glyphs.map((g, i) => toD(g.getPath(originX[i] + WORD_X - box.x1, baseline, size).commands)).join(' ');
const wordWidth = Math.ceil(box.x2 - box.x1);
const fullW = WORD_X + wordWidth;
const fullH = 64;

const lockup = (ink) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${fullW} ${fullH}" width="${fullW}" height="${fullH}">` +
  `<title>ZKSona</title>${markSvg()}<path d="${wordD}" fill="${ink}"/></svg>\n`;

const brandDir = path.join(root, 'public/brand');
fs.mkdirSync(brandDir, { recursive: true });
fs.writeFileSync(path.join(brandDir, 'logo.svg'), lockup(INK));
fs.writeFileSync(path.join(brandDir, 'logo-dark.svg'), lockup(PAPER));

const markFile = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64"><title>ZKSona</title>${markSvg()}</svg>\n`;
fs.writeFileSync(path.join(root, 'public/favicon.svg'), markFile);
fs.writeFileSync(path.join(brandDir, 'mark.svg'), markFile);

// PNG exports: 500x500, lockup centred with ~12% padding
const render = (svg, width) => new Resvg(svg, { fitTo: { mode: 'width', value: width } }).render().asPng();
const pad = 500 * 0.12;
const scale = (500 - pad * 2) / fullW;
const png = (bg) => {
  const ty = (500 - fullH * scale) / 2;
  return render(
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500" width="500" height="500">` +
      (bg ? `<rect width="500" height="500" fill="${bg}"/>` : '') +
      `<g transform="translate(${pad} ${ty}) scale(${scale})">${markSvg()}<path d="${wordD}" fill="${INK}"/></g></svg>`,
    500,
  );
};
fs.writeFileSync(path.join(brandDir, 'logo-500.png'), png(MIST));
fs.writeFileSync(path.join(brandDir, 'logo-500-transparent.png'), png(null));

// React data
fs.writeFileSync(
  path.join(root, 'src/data/logo.ts'),
  `// Generated by scripts/build-logo.mjs. Do not edit by hand.\n` +
    `export const LOGO = ${JSON.stringify({ width: fullW, height: fullH, mark, word: wordD, wordBox: { x: WORD_X, width: wordWidth } }, null, 2)} as const;\n`,
);
console.log('logo', fullW, fullH);

// Open Graph / Twitter card, 1200x630: ink panel, statement in the brand face (outlined), three index cards
{
  const line = (text, s, x, y) => {
    const glyphsL = [...text].map((ch) => font.charToGlyph(ch));
    let cx = x;
    return glyphsL
      .map((g, i) => {
        const d = toD(g.getPath(cx, y, s).commands);
        const next = glyphsL[i + 1];
        const kern = next ? font.getKerningValue(g, next) : 0;
        cx += ((g.advanceWidth + (Number.isFinite(kern) ? kern : 0)) / font.unitsPerEm) * s - 0.03 * s;
        return d;
      })
      .join(' ');
  };
  const card = (x, y, w, h, fill, rot) =>
    `<g transform="rotate(${rot} ${x + w / 2} ${y + h / 2})"><rect x="${x}" y="${y}" width="${w}" height="${h}" rx="12" fill="${fill}"/></g>`;
  const og =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">` +
    `<rect width="1200" height="630" fill="${INK}"/>` +
    card(760, 150, 300, 380, SKY, 8) +
    card(720, 120, 300, 380, MINT, -4) +
    card(680, 100, 300, 380, ACCENT, 3) +
    `<g transform="translate(80 80) scale(1.1)">${markSvg()}<path d="${wordD}" fill="${PAPER}"/></g>` +
    `<path d="${line('Private', 118, 76, 380)}" fill="${PAPER}"/>` +
    `<path d="${line('by proof.', 118, 76, 490)}" fill="${ACCENT}"/>` +
    `<path d="${line('zksona.org', 30, 80, 566)}" fill="#999999"/>` +
    `</svg>`;
  fs.writeFileSync(path.join(root, 'public/og-image.png'), render(og, 1200));
}

// App icons: the mark, full bleed on its own tile
for (const [file, size] of [
  ['apple-touch-icon.png', 180],
  ['icon-192.png', 192],
  ['icon-512.png', 512],
]) {
  const svg = `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="${size}" height="${size}"><rect width="64" height="64" fill="${ACCENT}"/>${markSvg()}</svg>`;
  fs.writeFileSync(path.join(root, 'public', file), render(svg, size));
}
console.log('social + app icons');
