// Builds the Zentry logo from one source: the mark geometry below + the "zentry" wordmark
// outlined from Outfit Medium. Writes the React path data, the SVG files and the PNG exports.
// Run: node scripts/build-logo.mjs
import fs from 'node:fs';
import path from 'node:path';
import opentype from 'opentype.js';
import { Resvg } from '@resvg/resvg-js';

const root = path.resolve(import.meta.dirname, '..');
const INK = '#0a0a0c';
const ACCENT = '#6d45ff';
const ACCENT_DEEP = '#5a33e6';
const ACCENT_SOFT = '#f1ecff';
const SURFACE = '#ffffff';

// Mark: a violet shield with a Z-shaped channel cut through it. The Z is the name's initial and
// the route a private transaction takes: in at the top, across, out at the bottom. 64-unit grid.
const shield = 'M32 4 L54 11.5 V29 C54 44 44.5 54.5 32 60 C19.5 54.5 10 44 10 29 V11.5 Z';
const z = 'M20 15 H44 V21 L28.5 37 H44 V43 H20 V37 L35.5 21 H20 Z';
const cy = 18;
const r = 30; // lockup baseline sits at cy + r = 48
// Wordmark
const font = opentype.parse(fs.readFileSync(path.join(root, 'scripts/fonts/Outfit-Medium.ttf')).buffer);
const size = 62;
const tracking = -0.01 * size;
const word = 'zentry';
const advance = (i) => {
  const g = glyphs[i];
  const next = glyphs[i + 1];
  const rawKern = next ? font.getKerningValue(g, next) : 0;
  const kern = Number.isFinite(rawKern) ? rawKern : 0;
  // The space glyph in this font carries no advance width, so fall back to a word space.
  const aw = Number.isFinite(g.advanceWidth) && g.advanceWidth > 0 ? g.advanceWidth : font.unitsPerEm * 0.24;
  return ((aw + kern) / font.unitsPerEm) * size + tracking;
};
const glyphs = [...word].map((ch) => font.charToGlyph(ch));
const originX = glyphs.map((_, i) => glyphs.slice(0, i).reduce((sum, __, k) => sum + advance(k), 0));
// Bounding box of the outlined word (baseline at y=0)
const wordBox = { x1: Infinity, x2: -Infinity };
glyphs.forEach((g, i) => {
  const b = g.getPath(originX[i], 0, size).getBoundingBox();
  wordBox.x1 = Math.min(wordBox.x1, b.x1);
  wordBox.x2 = Math.max(wordBox.x2, b.x2);
});
const x2 = wordBox.x2;
// Place the word: baseline at y=48, level with the widest part of the shield
const baseline = cy + r; // 48
const wordOffsetX = 76 - wordBox.x1;
// opentype.js's toPathData() emits NaN for some coordinates in this font, so serialise the commands directly.
const n2 = (v) => (Math.round(v * 100) / 100).toString();
const toD = (commands) =>
  commands
    .map((c) => {
      if (c.type === 'M' || c.type === 'L') return `${c.type}${n2(c.x)} ${n2(c.y)}`;
      if (c.type === 'Q') return `Q${n2(c.x1)} ${n2(c.y1)} ${n2(c.x)} ${n2(c.y)}`;
      if (c.type === 'C') return `C${n2(c.x1)} ${n2(c.y1)} ${n2(c.x2)} ${n2(c.y2)} ${n2(c.x)} ${n2(c.y)}`;
      return 'Z';
    })
    .join('');
const wordD = glyphs.map((g, i) => toD(g.getPath(originX[i] + wordOffsetX, baseline, size).commands)).join(' ');
const fullW = Math.ceil(76 + (x2 - wordBox.x1));
const fullH = 64;

const markSvg = (shieldFill = ACCENT, zFill = SURFACE) => `<path d="${shield}" fill="${shieldFill}"/><path d="${z}" fill="${zFill}"/>`;

const lockup = (ink) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${fullW} ${fullH}" width="${fullW}" height="${fullH}">` +
  `<title>Zentry</title>${markSvg()}<path d="${wordD}" fill="${ink}"/></svg>\n`;

const brandDir = path.join(root, 'public/brand');
fs.mkdirSync(brandDir, { recursive: true });
fs.writeFileSync(path.join(brandDir, 'logo.svg'), lockup(INK));
fs.writeFileSync(path.join(brandDir, 'logo-dark.svg'), lockup(SURFACE));

const markFile = (bg) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64"><title>Zentry</title>` +
  (bg ? `<rect width="64" height="64" rx="14" fill="${bg}"/>` : '') +
  `<g transform="translate(1.6 1.6) scale(0.95)">${markSvg()}</g></svg>\n`;
fs.writeFileSync(path.join(root, 'public/favicon.svg'), markFile(null));
fs.writeFileSync(path.join(brandDir, 'mark.svg'), markFile(null));

// PNG exports: 500x500, lockup centred with ~12% padding
const pad = 500 * 0.12;
const inner = 500 - pad * 2;
const scale = inner / fullW;
const png = (bg) => {
  const ty = (500 - fullH * scale) / 2;
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500" width="500" height="500">` +
    (bg ? `<rect width="500" height="500" fill="${bg}"/>` : '') +
    `<g transform="translate(${pad} ${ty}) scale(${scale})">${markSvg()}<path d="${wordD}" fill="${INK}"/></g></svg>`;
  return new Resvg(svg, { fitTo: { mode: 'width', value: 500 }, background: bg ? undefined : 'rgba(0,0,0,0)' })
    .render()
    .asPng();
};
fs.writeFileSync(path.join(brandDir, 'logo-500.png'), png(ACCENT_SOFT));
fs.writeFileSync(path.join(brandDir, 'logo-500-transparent.png'), png(null));

// React data
fs.writeFileSync(
  path.join(root, 'src/data/logo.ts'),
  `// Generated by scripts/build-logo.mjs. Do not edit by hand.\n` +
    `export const LOGO = ${JSON.stringify({ width: fullW, height: fullH, shield, z, word: wordD, wordBox: { x: 76, width: Math.ceil(x2 - wordBox.x1) } }, null, 2)} as const;\n`,
);
console.log('logo', fullW, fullH);

// ---------- Social + app icons ----------
const fontFiles = [path.join(root, 'scripts/fonts/Outfit-Medium.ttf'), path.join(root, 'scripts/fonts/Outfit-Light.ttf')];
const render = (svg, width) =>
  new Resvg(svg, {
    fitTo: { mode: 'width', value: width },
    font: { fontFiles, loadSystemFonts: false, defaultFontFamily: 'Outfit' },
  })
    .render()
    .asPng();

// Open Graph / Twitter card, 1200x630
{
  const lockScale = 3;
  const og =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">` +
    `<defs><radialGradient id="g" cx="0.12" cy="0.2" r="0.9">` +
    `<stop offset="0" stop-color="#a586ff"/><stop offset="0.45" stop-color="#e3d9ff"/><stop offset="1" stop-color="#f7f7f8"/></radialGradient></defs>` +
    `<rect width="1200" height="630" fill="url(#g)"/>` +
    `<g transform="translate(88 96) scale(${lockScale})">${markSvg()}<path d="${wordD}" fill="${INK}"/></g>` +
    `<text x="92" y="410" font-family="Outfit" font-weight="300" font-size="78" fill="${INK}">Move value</text>` +
    `<text x="92" y="496" font-family="Outfit" font-weight="300" font-size="78" fill="${INK}">without a trail.</text>` +
    `<text x="96" y="566" font-family="Outfit" font-weight="500" font-size="26" fill="${ACCENT_DEEP}">Zero-knowledge privacy on Solana  ·  zentry-shield.xyz</text>` +
    `</svg>`;
  fs.writeFileSync(path.join(root, 'public/og-image.png'), render(og, 1200));
}

// App icons: mark on the brand surface, centred with padding
const iconSvg = (size) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="${size}" height="${size}">` +
  `<rect width="64" height="64" fill="${ACCENT_SOFT}"/>` +
  `<g transform="translate(8.8 8.8) scale(0.725)">${markSvg()}</g></svg>`;
for (const [file, size] of [
  ['apple-touch-icon.png', 180],
  ['icon-192.png', 192],
  ['icon-512.png', 512],
]) {
  fs.writeFileSync(path.join(root, 'public', file), render(iconSvg(size), size));
}
console.log('social + app icons');
