// Builds the Nix Shield logo from one source: the mark geometry below + the "nix shield" wordmark
// outlined from Outfit Medium. Writes the React path data, the SVG files and the PNG exports.
// Run: node scripts/build-logo.mjs
import fs from 'node:fs';
import path from 'node:path';
import opentype from 'opentype.js';
import { Resvg } from '@resvg/resvg-js';

const root = path.resolve(import.meta.dirname, '..');
const INK = '#0c0b10';
const ACCENT = '#7df0c0';
const ACCENT_DEEP = '#0e9467';
const SURFACE = '#ffffff';

// Mark: a shield with a redaction bar across it. "Nix" as in blanked out: the shield keeps
// what is behind the bar unreadable. 64-unit grid.
const shield = 'M32 4 L54 11.5 V29 C54 44 44.5 54.5 32 60 C19.5 54.5 10 44 10 29 V11.5 Z';
const bar = { x: 17, y: 25, w: 30, h: 9, r: 2.5 };
const cy = 18;
const r = 30; // lockup baseline sits at cy + r = 48
// Wordmark
const font = opentype.parse(fs.readFileSync(path.join(root, 'scripts/fonts/Outfit-Medium.ttf')).buffer);
const size = 62;
const tracking = -0.01 * size;
const word = 'nix shield';
const advance = (i) => {
  const g = glyphs[i];
  const next = glyphs[i + 1];
  const rawKern = next ? font.getKerningValue(g, next) : 0;
  const kern = Number.isFinite(rawKern) ? rawKern : 0;
  // The space glyph in this font carries no advance width, so fall back to a word space.
  const aw = Number.isFinite(g.advanceWidth) && g.advanceWidth > 0 ? g.advanceWidth : font.unitsPerEm * 0.24;
  return ((aw + kern) / font.unitsPerEm) * size + tracking;
};
const glyphs = [...word].map((ch) => font.charToGlyph(ch));
const originX = glyphs.map((_, i) => glyphs.slice(0, i).reduce((sum, __, k) => sum + advance(k), 0));
// Bounding box of the outlined word (baseline at y=0)
const wordBox = { x1: Infinity, x2: -Infinity };
glyphs.forEach((g, i) => {
  const b = g.getPath(originX[i], 0, size).getBoundingBox();
  wordBox.x1 = Math.min(wordBox.x1, b.x1);
  wordBox.x2 = Math.max(wordBox.x2, b.x2);
});
const x2 = wordBox.x2;
// Place the word: baseline at y=48, level with the widest part of the shield
const baseline = cy + r; // 48
const wordOffsetX = 76 - wordBox.x1;
// opentype.js's toPathData() emits NaN for some coordinates in this font, so serialise the commands directly.
const n2 = (v) => (Math.round(v * 100) / 100).toString();
const toD = (commands) =>
  commands
    .map((c) => {
      if (c.type === 'M' || c.type === 'L') return `${c.type}${n2(c.x)} ${n2(c.y)}`;
      if (c.type === 'Q') return `Q${n2(c.x1)} ${n2(c.y1)} ${n2(c.x)} ${n2(c.y)}`;
      if (c.type === 'C') return `C${n2(c.x1)} ${n2(c.y1)} ${n2(c.x2)} ${n2(c.y2)} ${n2(c.x)} ${n2(c.y)}`;
      return 'Z';
    })
    .join('');
const wordD = glyphs.map((g, i) => toD(g.getPath(originX[i] + wordOffsetX, baseline, size).commands)).join(' ');
const fullW = Math.ceil(76 + (x2 - wordBox.x1));
const fullH = 64;

const markSvg = (inkFill, barFill) =>
  `<path d="${shield}" fill="${inkFill}"/>` +
  `<rect x="${bar.x}" y="${bar.y}" width="${bar.w}" height="${bar.h}" rx="${bar.r}" fill="${barFill}"/>`;

const lockup = (ink, dot) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 ${fullW} ${fullH}" width="${fullW}" height="${fullH}">` +
  `<title>Nix Shield</title>${markSvg(ink, dot)}<path d="${wordD}" fill="${ink}"/></svg>\n`;

const brandDir = path.join(root, 'public/brand');
fs.mkdirSync(brandDir, { recursive: true });
fs.writeFileSync(path.join(brandDir, 'logo.svg'), lockup(INK, ACCENT));
fs.writeFileSync(path.join(brandDir, 'logo-dark.svg'), lockup(SURFACE, ACCENT_DEEP));

const markFile = (bg) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="64" height="64"><title>Nix Shield</title>` +
  (bg ? `<rect width="64" height="64" rx="14" fill="${bg}"/>` : '') +
  `<g transform="translate(1.6 1.6) scale(0.95)">${markSvg(ACCENT, INK)}</g></svg>\n`;
fs.writeFileSync(path.join(root, 'public/favicon.svg'), markFile(null));
fs.writeFileSync(path.join(brandDir, 'mark.svg'), markFile(null));

// PNG exports: 500x500, lockup centred with ~12% padding
const pad = 500 * 0.12;
const inner = 500 - pad * 2;
const scale = inner / fullW;
const png = (bg) => {
  const ty = (500 - fullH * scale) / 2;
  const svg =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 500 500" width="500" height="500">` +
    (bg ? `<rect width="500" height="500" fill="${bg}"/>` : '') +
    `<g transform="translate(${pad} ${ty}) scale(${scale})">${markSvg(INK, ACCENT)}<path d="${wordD}" fill="${INK}"/></g></svg>`;
  return new Resvg(svg, { fitTo: { mode: 'width', value: 500 }, background: bg ? undefined : 'rgba(0,0,0,0)' })
    .render()
    .asPng();
};
fs.writeFileSync(path.join(brandDir, 'logo-500.png'), png('#effcf6'));
fs.writeFileSync(path.join(brandDir, 'logo-500-transparent.png'), png(null));

// React data
fs.writeFileSync(
  path.join(root, 'src/data/logo.ts'),
  `// Generated by scripts/build-logo.mjs. Do not edit by hand.\n` +
    `export const LOGO = ${JSON.stringify({ width: fullW, height: fullH, shield, bar, word: wordD, wordBox: { x: 76, width: Math.ceil(x2 - wordBox.x1) } }, null, 2)} as const;\n`,
);
console.log('logo', fullW, fullH);

// ---------- Social + app icons ----------
const fontFiles = [path.join(root, 'scripts/fonts/Outfit-Medium.ttf'), path.join(root, 'scripts/fonts/Outfit-Light.ttf')];
const render = (svg, width) =>
  new Resvg(svg, {
    fitTo: { mode: 'width', value: width },
    font: { fontFiles, loadSystemFonts: false, defaultFontFamily: 'Outfit' },
  })
    .render()
    .asPng();

// Open Graph / Twitter card, 1200x630
{
  const lockScale = 3;
  const og =
    `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 1200 630" width="1200" height="630">` +
    `<defs><radialGradient id="g" cx="0.12" cy="0.2" r="0.9">` +
    `<stop offset="0" stop-color="#7df0c0"/><stop offset="0.45" stop-color="#d6fbea"/><stop offset="1" stop-color="#f7faf9"/></radialGradient></defs>` +
    `<rect width="1200" height="630" fill="url(#g)"/>` +
    `<g transform="translate(88 96) scale(${lockScale})">${markSvg(INK, ACCENT)}<path d="${wordD}" fill="${INK}"/></g>` +
    `<text x="92" y="410" font-family="Outfit" font-weight="300" font-size="78" fill="${INK}">Move value</text>` +
    `<text x="92" y="496" font-family="Outfit" font-weight="300" font-size="78" fill="${INK}">without a trail.</text>` +
    `<text x="96" y="566" font-family="Outfit" font-weight="500" font-size="26" fill="#0e9467">Zero-knowledge privacy infrastructure  ·  nixshield.org</text>` +
    `</svg>`;
  fs.writeFileSync(path.join(root, 'public/og-image.png'), render(og, 1200));
}

// App icons: mark on the brand surface, centred with padding
const iconSvg = (size) =>
  `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64" width="${size}" height="${size}">` +
  `<rect width="64" height="64" fill="#effcf6"/>` +
  `<g transform="translate(8.8 8.8) scale(0.725)">${markSvg(INK, ACCENT)}</g></svg>`;
for (const [file, size] of [
  ['apple-touch-icon.png', 180],
  ['icon-192.png', 192],
  ['icon-512.png', 512],
]) {
  fs.writeFileSync(path.join(root, 'public', file), render(iconSvg(size), size));
}
console.log('social + app icons');
